version: "3.9"

services:
  localstack:
    image: localstack/localstack:3.8.1
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,iam,lambda,apigateway,cloudfront,sts,ec2
      - DEFAULT_REGION=us-east-1
      - EAGER_SERVICE_LOADING=1
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  localstack_data:
